version: "3.3" 
services:
  overseerr:
    container_name: overseerr
    restart: always
    network_mode: host
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    image: sctx/overseerr:latest
    ports:
      - "5055:5055"
    volumes:
      - /mnt/bigpool/big/configs/overseerr:/app/config
  plex:
    container_name: plex
    environment:
      - VERSION=latest
      - TZ=America/New_York
    image: linuxserver/plex
    network_mode: host
    restart: always
    ports:
      - "32400:32400"
    volumes:
      - /mnt/bigpool/big/configs/plex:/config
      - /mnt/bigpool/big/media/movies:/data/movies
      - /mnt/bigpool/big/media/tv:/data/tvshows
      - /mnt/bigpool/big/media/racing:/data/racing
      - /mnt/bigpool/big/media/transcode:/data/transcode
  portainer:
    container_name: portainer
    environment:
      - TZ=America/New_York
    image: portainer/portainer
    ports:
      - "9000:9000"
    restart: always
    network_mode: host
    volumes:
      - /mnt/bigpool/big/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  # qbittorrent:
  #   container_name: qbittorrent
  #   depends_on:
  #     - sabnzbd
  #   environment:
  #     - TZ=America/New_York
  #   image: linuxserver/qbittorrent
  #   ports:
  #     - "6881:6881/tcp"
  #     - "6881:6881/udp"
  #   restart: always
  #   network_mode: host
  #   volumes:
  #     - /mnt/bigpool/big/data/torrents:/data
  #     - /mnt/bigpool/big/data/torrents/logs:/var/log/qbittorrent
  radarr:
    container_name: radarr
    depends_on:
      - sabnzbd
    environment:
      - TZ=America/New_York
    image: linuxserver/radarr
    ports:
      - "7878:7878"
    restart: always
    network_mode: host
    volumes:
      - /mnt/bigpool/big/configs/radarr:/config
      - /mnt/bigpool/big/data/usenet:/downloads
      - /mnt/bigpool/big/media/movies:/movies
  sabnzbd:
    container_name: sabnzbd
    restart: always
    network_mode: host
    environment:
      - TZ=America/New_York
    image: linuxserver/sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - /mnt/bigpool/big/configs/sabnzbd:/config
      - /mnt/bigpool/big/data/usenet:/downloads
      - /mnt/bigpool/big/data/usenet/incomplete:/incomplete-downloads
  sonarr:
    container_name: sonarr
    depends_on:
      - sabnzbd
    environment:
      - TZ=America/New_York
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    restart: always
    network_mode: host
    volumes:
      - /mnt/bigpool/big/configs/sonarr:/config
      - /mnt/bigpool/big/data/usenet:/downloads
      - /mnt/bigpool/big/media/tv:/tv
  watchtower:
    container_name: watchtower
    environment:
      - TZ=America/New_York
    image: v2tec/watchtower
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
