version: "3.3"
services:

  # port 5055
  overseerr:
    container_name: overseerr
    restart: always
    network_mode: host
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    image: sctx/overseerr:latest
    volumes:
      - /mnt/bigpool/big/configs/overseerr:/app/config

  # port :32400/web
  plex:
    container_name: plex
    environment:
      - VERSION=latest
      - TZ=America/New_York
    image: linuxserver/plex
    network_mode: host
    restart: always
    volumes:
      - /mnt/bigpool/big/configs/plex:/config
      - /mnt/bigpool/big/media/movies:/data/movies
      - /mnt/bigpool/big/media/tv:/data/tvshows
      - /mnt/bigpool/big/media/racing:/data/racing
      - /mnt/bigpool/big/media/transcode:/data/transcode
    devices:
     - /dev/dri:/dev/dri

  # port 9000
  portainer:
    container_name: portainer
    environment:
      - TZ=America/New_York
    image: portainer/portainer
    restart: always
    network_mode: host
    volumes:
      - /mnt/bigpool/big/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # port 7878
  radarr:
    container_name: radarr
    depends_on:
      - sabnzbd
    environment:
      - TZ=America/New_York
    image: linuxserver/radarr
    restart: always
    network_mode: host
    volumes:
      - /mnt/bigpool/big/configs/radarr:/config
      - /mnt/bigpool/big/data/usenet:/downloads
      - /mnt/bigpool/big/media/movies:/movies

  # port 8080
  sabnzbd:
    container_name: sabnzbd
    restart: always
    network_mode: host
    environment:
      - TZ=America/New_York
    image: linuxserver/sabnzbd
    volumes:
      - /mnt/bigpool/big/configs/sabnzbd:/config
      - /mnt/bigpool/big/data/usenet:/downloads
      - /mnt/bigpool/big/data/usenet/incomplete:/incomplete-downloads

  # port 8989
  sonarr:
    container_name: sonarr
    depends_on:
      - sabnzbd
    environment:
      - TZ=America/New_York
    image: linuxserver/sonarr
    restart: always
    network_mode: host
    volumes:
      - /mnt/bigpool/big/configs/sonarr:/config
      - /mnt/bigpool/big/data/usenet:/downloads
      - /mnt/bigpool/big/media/tv:/tv

  # no port
  watchtower:
    container_name: watchtower
    environment:
      - TZ=America/New_York
    image: v2tec/watchtower
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
