
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    volumes:
      - ${ROOT}/configs/plex:/config
      - ${ROOT}/media/movies:/data/movies
      - ${ROOT}/media/tv:/data/tvshows
      - ${ROOT}/media/racing:/data/racing
      - ${ROOT}/media/transcode:/data/transcode
    network_mode: host
    environment:
      - VERSION=latest
      - TZ=America/New_York
  sabnzbd:
    image: linuxserver/sabnzbd
    ports:
      - 8080:8080
    volumes:
      - ${ROOT}/configs/sabnzbd:/config
      - ${ROOT}/data/usenet:/downloads
      - ${ROOT}/data/usenet/incomplete:/incomplete-downloads
    environment:
      - TZ=America/New_York
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    depends_on:
      - sabnzbd
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - ${ROOT}/data/torrents:/data
      - ${ROOT}/data/torrents/logs:/var/log/qbittorrent
    environment:
      - TZ=America/New_York
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    depends_on:
      - sabnzbd
    volumes:
      - ${ROOT}/configs/sonarr:/config
      - ${ROOT}/data/usenet:/downloads
      - ${ROOT}/media/tv:/tv
    environment:
      - TZ=America/New_York
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    depends_on:
      - sabnzbd
    volumes:
      - ${ROOT}/configs/radarr:/config
      - ${ROOT}/data/usenet:/downloads
      - ${ROOT}/media/movies:/movies
    environment:
      - TZ=America/New_York
    ports:
      - 7878:7878
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: always
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - ${ROOT}/configs/overseerr:/app/config
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    environment:
      - TZ=America/New_York
    volumes:
      - ${ROOT}/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
